### ISSUE TITLE
Camp definitions in Kripke and Umpire.

### ISSUE THREAD

**Issue by rchen20** [LLNL/Kripke#29]
The new Umpire specifies a Camp submodule, which conflicts with the definition of Camp in the Kripke build system. Need the appropriate Cmake to choose one (Umpire uses Camp v0.2.2, Kripke has Camp v0.2.3).

**Comment by rhornung67** [comment]
@davidbeckingsale the latest releases of RAJA and Umpire are on camp v0.2.2, but Kripke is on v0.2.3. Is the best way to resolve this issue to point RAJA and Umpire at the Kripke sub-module?

**Comment by davidbeckingsale** [comment]
If the Kripke camp version gets loaded first, it should take precedence - the Umpire CMake skips the submodule if a `camp` Cmake target already exists, and so does RAJA's.

**Comment by rhornung67** [comment]
I thought it worked something like that. @rchen20 does this make sense?

**Comment by ajkunen** [comment]
@rchen20  are you getting a build error with Kripke specifying camp 0.2.3?

**Comment by rchen20** [comment]
@rhornung67 @ajkunen Kripke is finding Umpire's version of Camp first, and then right before it looks for RAJA, it tries to find a suitable version of Camp. During this check, it thinks it found a Camp (Umpire's), but tries to find Camp anyway by searching for a `camp-config.cmake`. I'm going to continue looking in to this and will see if I can switch the ordering of Camp find's as @davidbeckingsale suggested.

**Comment by ajkunen** [comment]
@rchen20 I don't think Kripke needs anything in camp 0.2.3 that isn't in 0.2.2.
Could we just switch Kripke to pull in the Umpire camp instead?  That would be one less dependency that Kripke needs to directly manage.

**Comment by rchen20** [comment]
> @rchen20 I don't think Kripke needs anything in camp 0.2.3 that isn't in 0.2.2.
> Could we just switch Kripke to pull in the Umpire camp instead? That would be one less dependency that Kripke needs to directly manage.

Yeah I was trying to do that yesterday and almost got there. As long as the Umpire and RAJA releases are on the same Camp (which I think is true @rhornung67 ), then this should work. When I get this to work, shall I just remove the tpl/camp directory from the Kripke repo?

**Comment by ajkunen** [comment]
@rchen20 yeah, removing tpl/camp would be great

**Comment by rhornung67** [comment]
@rchen20 latest RAJA and Umpire releases are both on camp v0.2.2

**Comment by rchen20** [comment]
This will be fixed in here https://github.com/LLNL/Kripke/pull/30 (thanks @vsrana01 !), which just removes `tpl/camp`.

**Comment by vsrana01** [comment]
see #33
