### ISSUE TITLE
Is there any AVX/FMA build versions for Kripke

### ISSUE THREAD

**Issue by lalith-mcw** [LLNL/Kripke#45]
https://openbenchmarking.org/test/pts/kripke&eval=92ea8c6bc626ac98038ab684f1a6b194e7581d6c

Could see here in `Notable Instruction Set Usage` section

**Comment by rchen20** [comment]
There are no versions of Kripke with intrinsics. Any vector or FMA instructions detected are likely due to `-O3` optimization. Let me know if this is what you're looking for.
