### ISSUE TITLE
Build Failing In quartz

### ISSUE THREAD

**Issue by Saptarshibh** [LLNL/Kripke#7]
While trying to build Kripke in Quartz. The build is failing, the errors are as follow
========================================================================
[ 31%] Building CXX object CMakeFiles/kripke.dir/src/Kripke/Generate/Data.cpp.o
In file included from /g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/InputVariables.h:37:0,
                 from /g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/Generate.h:38,
                 from /g/g92/bhowmik1/Kripke/Kripke/src/Kripke/Generate/Data.cpp:33:
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h: In function 'void Kripke::dispatch(Kripke::ArchLayoutV, const Function&, Args&& ...)':
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:189:32: warning: use of 'auto' in lambda parameter declaration only available with -std=c++1y or -std=gnu++1y
   dispatchArch(al_v.arch_v, [&](auto arch_t){
                                ^
In file included from /g/g92/bhowmik1/Kripke/Kripke/src/Kripke/Generate/Data.cpp:41:0:
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/VarTypes.h: In function 'FieldType& Kripke::createField(Kripke::Core::DataStore&, const string&, Kripke::ArchLayoutV, const SetType&)':
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/VarTypes.h:169:38: warning: use of 'auto' in lambda parameter declaration only available with -std=c++1y or -std=gnu++1y
     dispatchLayout(al_v.layout_v, [&](auto layout_t){
                                      ^
In file included from /g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/InputVariables.h:37:0,
                 from /g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/Generate.h:38,
                 from /g/g92/bhowmik1/Kripke/Kripke/src/Kripke/Generate/Data.cpp:33:
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h: In instantiation of 'void Kripke::dispatchLayout(Kripke::LayoutV, const Function&, Args&& ...) [with Function = Kripke::createField(Kripke::Core::DataStore&, const string&, Kripke::ArchLayoutV, const SetType&) [with FieldType = Kripke::Core::Field<double, Kripke::Direction, Kripke::Group, Kripke::Zone>; SetType = Kripke::Core::ProductSet<3ul>; std::string = std::basic_string<char>]::<lambda(auto:2)>; Args = {}]':
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/VarTypes.h:174:6:   required from 'FieldType& Kripke::createField(Kripke::Core::DataStore&, const string&, Kripke::ArchLayoutV, const SetType&) [with FieldType = Kripke::Core::Field<double, Kripke::Direction, Kripke::Group, Kripke::Zone>; SetType = Kripke::Core::ProductSet<3ul>; std::string = std::basic_string<char>]'
/g/g92/bhowmik1/Kripke/Kripke/src/Kripke/Generate/Data.cpp:66:61:   required from here
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:147:69: error: invalid use of 'auto'
     case LayoutV_DGZ: fcn(LayoutT_DGZ{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:148:69: error: invalid use of 'auto'
     case LayoutV_DZG: fcn(LayoutT_DZG{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:149:69: error: invalid use of 'auto'
     case LayoutV_GDZ: fcn(LayoutT_GDZ{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:150:69: error: invalid use of 'auto'
     case LayoutV_GZD: fcn(LayoutT_GZD{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:151:69: error: invalid use of 'auto'
     case LayoutV_ZDG: fcn(LayoutT_ZDG{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:152:69: error: invalid use of 'auto'
     case LayoutV_ZGD: fcn(LayoutT_ZGD{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h: In instantiation of 'void Kripke::dispatchLayout(Kripke::LayoutV, const Function&, Args&& ...) [with Function = Kripke::createField(Kripke::Core::DataStore&, const string&, Kripke::ArchLayoutV, const SetType&) [with FieldType = Kripke::Core::Field<double, Kripke::Moment, Kripke::Group, Kripke::Zone>; SetType = Kripke::Core::ProductSet<3ul>; std::string = std::basic_string<char>]::<lambda(auto:2)>; Args = {}]':
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/VarTypes.h:174:6:   required from 'FieldType& Kripke::createField(Kripke::Core::DataStore&, const string&, Kripke::ArchLayoutV, const SetType&) [with FieldType = Kripke::Core::Field<double, Kripke::Moment, Kripke::Group, Kripke::Zone>; SetType = Kripke::Core::ProductSet<3ul>; std::string = std::basic_string<char>]'
/g/g92/bhowmik1/Kripke/Kripke/src/Kripke/Generate/Data.cpp:79:70:   required from here
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:147:69: error: invalid use of 'auto'
     case LayoutV_DGZ: fcn(LayoutT_DGZ{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:148:69: error: invalid use of 'auto'
     case LayoutV_DZG: fcn(LayoutT_DZG{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:149:69: error: invalid use of 'auto'
     case LayoutV_GDZ: fcn(LayoutT_GDZ{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:150:69: error: invalid use of 'auto'
     case LayoutV_GZD: fcn(LayoutT_GZD{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:151:69: error: invalid use of 'auto'
     case LayoutV_ZDG: fcn(LayoutT_ZDG{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:152:69: error: invalid use of 'auto'
     case LayoutV_ZGD: fcn(LayoutT_ZGD{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h: In instantiation of 'void Kripke::dispatchLayout(Kripke::LayoutV, const Function&, Args&& ...) [with Function = Kripke::createField(Kripke::Core::DataStore&, const string&, Kripke::ArchLayoutV, const SetType&) [with FieldType = Kripke::Core::Field<double, Kripke::Direction, Kripke::Group, Kripke::ZoneJ, Kripke::ZoneK>; SetType = Kripke::Core::Set; std::string = std::basic_string<char>]::<lambda(auto:2)>; Args = {}]':
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/VarTypes.h:174:6:   required from 'FieldType& Kripke::createField(Kripke::Core::DataStore&, const string&, Kripke::ArchLayoutV, const SetType&) [with FieldType = Kripke::Core::Field<double, Kripke::Direction, Kripke::Group, Kripke::ZoneJ, Kripke::ZoneK>; SetType = Kripke::Core::Set; std::string = std::basic_string<char>]'
/g/g92/bhowmik1/Kripke/Kripke/src/Kripke/Generate/Data.cpp:90:68:   required from here
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:147:69: error: invalid use of 'auto'
     case LayoutV_DGZ: fcn(LayoutT_DGZ{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:148:69: error: invalid use of 'auto'
     case LayoutV_DZG: fcn(LayoutT_DZG{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:149:69: error: invalid use of 'auto'
     case LayoutV_GDZ: fcn(LayoutT_GDZ{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:150:69: error: invalid use of 'auto'
     case LayoutV_GZD: fcn(LayoutT_GZD{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:151:69: error: invalid use of 'auto'
     case LayoutV_ZDG: fcn(LayoutT_ZDG{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:152:69: error: invalid use of 'auto'
     case LayoutV_ZGD: fcn(LayoutT_ZGD{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h: In instantiation of 'void Kripke::dispatchLayout(Kripke::LayoutV, const Function&, Args&& ...) [with Function = Kripke::createField(Kripke::Core::DataStore&, const string&, Kripke::ArchLayoutV, const SetType&) [with FieldType = Kripke::Core::Field<double, Kripke::Direction, Kripke::Group, Kripke::ZoneI, Kripke::ZoneK>; SetType = Kripke::Core::Set; std::string = std::basic_string<char>]::<lambda(auto:2)>; Args = {}]':
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/VarTypes.h:174:6:   required from 'FieldType& Kripke::createField(Kripke::Core::DataStore&, const string&, Kripke::ArchLayoutV, const SetType&) [with FieldType = Kripke::Core::Field<double, Kripke::Direction, Kripke::Group, Kripke::ZoneI, Kripke::ZoneK>; SetType = Kripke::Core::Set; std::string = std::basic_string<char>]'
/g/g92/bhowmik1/Kripke/Kripke/src/Kripke/Generate/Data.cpp:91:68:   required from here
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:147:69: error: invalid use of 'auto'
     case LayoutV_DGZ: fcn(LayoutT_DGZ{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:148:69: error: invalid use of 'auto'
     case LayoutV_DZG: fcn(LayoutT_DZG{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:149:69: error: invalid use of 'auto'
     case LayoutV_GDZ: fcn(LayoutT_GDZ{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:150:69: error: invalid use of 'auto'
     case LayoutV_GZD: fcn(LayoutT_GZD{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:151:69: error: invalid use of 'auto'
     case LayoutV_ZDG: fcn(LayoutT_ZDG{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:152:69: error: invalid use of 'auto'
     case LayoutV_ZGD: fcn(LayoutT_ZGD{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h: In instantiation of 'void Kripke::dispatchLayout(Kripke::LayoutV, const Function&, Args&& ...) [with Function = Kripke::createField(Kripke::Core::DataStore&, const string&, Kripke::ArchLayoutV, const SetType&) [with FieldType = Kripke::Core::Field<double, Kripke::Direction, Kripke::Group, Kripke::ZoneI, Kripke::ZoneJ>; SetType = Kripke::Core::Set; std::string = std::basic_string<char>]::<lambda(auto:2)>; Args = {}]':
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/VarTypes.h:174:6:   required from 'FieldType& Kripke::createField(Kripke::Core::DataStore&, const string&, Kripke::ArchLayoutV, const SetType&) [with FieldType = Kripke::Core::Field<double, Kripke::Direction, Kripke::Group, Kripke::ZoneI, Kripke::ZoneJ>; SetType = Kripke::Core::Set; std::string = std::basic_string<char>]'
/g/g92/bhowmik1/Kripke/Kripke/src/Kripke/Generate/Data.cpp:92:68:   required from here
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:147:69: error: invalid use of 'auto'
     case LayoutV_DGZ: fcn(LayoutT_DGZ{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:148:69: error: invalid use of 'auto'
     case LayoutV_DZG: fcn(LayoutT_DZG{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:149:69: error: invalid use of 'auto'
     case LayoutV_GDZ: fcn(LayoutT_GDZ{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:150:69: error: invalid use of 'auto'
     case LayoutV_GZD: fcn(LayoutT_GZD{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:151:69: error: invalid use of 'auto'
     case LayoutV_ZDG: fcn(LayoutT_ZDG{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:152:69: error: invalid use of 'auto'
     case LayoutV_ZGD: fcn(LayoutT_ZGD{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h: In instantiation of 'void Kripke::dispatchLayout(Kripke::LayoutV, const Function&, Args&& ...) [with Function = Kripke::createField(Kripke::Core::DataStore&, const string&, Kripke::ArchLayoutV, const SetType&) [with FieldType = Kripke::Core::Field<double, Kripke::Material, Kripke::Legendre, Kripke::GlobalGroup, Kripke::GlobalGroup>; SetType = Kripke::Core::ProductSet<4ul>; std::string = std::basic_string<char>]::<lambda(auto:2)>; Args = {}]':
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/VarTypes.h:174:6:   required from 'FieldType& Kripke::createField(Kripke::Core::DataStore&, const string&, Kripke::ArchLayoutV, const SetType&) [with FieldType = Kripke::Core::Field<double, Kripke::Material, Kripke::Legendre, Kripke::GlobalGroup, Kripke::GlobalGroup>; SetType = Kripke::Core::ProductSet<4ul>; std::string = std::basic_string<char>]'
/g/g92/bhowmik1/Kripke/Kripke/src/Kripke/Generate/Data.cpp:105:69:   required from here
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:147:69: error: invalid use of 'auto'
     case LayoutV_DGZ: fcn(LayoutT_DGZ{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:148:69: error: invalid use of 'auto'
     case LayoutV_DZG: fcn(LayoutT_DZG{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:149:69: error: invalid use of 'auto'
     case LayoutV_GDZ: fcn(LayoutT_GDZ{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:150:69: error: invalid use of 'auto'
     case LayoutV_GZD: fcn(LayoutT_GZD{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:151:69: error: invalid use of 'auto'
     case LayoutV_ZDG: fcn(LayoutT_ZDG{}, std::forward<Args>(args)...); break;
                                                                     ^
/g/g92/bhowmik1/Kripke/Kripke/./src/Kripke/ArchLayout.h:152:69: error: invalid use of 'auto'
     case LayoutV_ZGD: fcn(LayoutT_ZGD{}, std::forward<Args>(args)...); break;
                                                                     ^
make[2]: *** [CMakeFiles/kripke.dir/src/Kripke/Generate/Data.cpp.o] Error 1
make[1]: *** [CMakeFiles/kripke.dir/all] Error 2
make: *** [all] Error 2

**Comment by davidbeckingsale** [comment]
You need to use different compiler flags: `warning: use of 'auto' in lambda parameter declaration only available with -std=c++1y or -std=gnu++1y`

**Comment by ajkunen** [comment]
This has been solved with the v1.2.3 release.  The build system should automatically add the proper -std=c++14 flag
